import type { Customer, ExtendedProduct } from "../types";

// Sample products for offline fallback (using ExtendedProduct with extra fields)
export const SAMPLE_PRODUCTS: ExtendedProduct[] = [
  {
    id: "prod-001",
    sku: "ELEC-001",
    nameCnSimplified: "",
    nameCnTraditional: "無線藍牙耳機",
    nameEn: "Wireless Bluetooth Headphones",
    category: "電子產品",
    categoryId: "CAT-ELEC",
    brand: "SoundMax",
    size: "One Size",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 120,
    promotions: "",
    price: 299,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-002",
    sku: "ELEC-002",
    nameCnSimplified: "",
    nameCnTraditional: "智能手錶",
    nameEn: "Smart Watch",
    category: "電子產品",
    categoryId: "CAT-ELEC",
    brand: "TechWear",
    size: "42mm",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 85,
    promotions: "",
    price: 599,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-003",
    sku: "CLOTH-001",
    nameCnSimplified: "",
    nameCnTraditional: "男士休閒襯衫",
    nameEn: "Men's Casual Shirt",
    category: "服裝",
    categoryId: "CAT-CLOTH",
    brand: "StyleCo",
    size: "M / L / XL",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 200,
    promotions: "Buy 2 Get 10% Off",
    price: 199,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-004",
    sku: "CLOTH-002",
    nameCnSimplified: "",
    nameCnTraditional: "女士運動褲",
    nameEn: "Women's Sport Pants",
    category: "服裝",
    categoryId: "CAT-CLOTH",
    brand: "ActiveFit",
    size: "S / M / L",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 45,
    promotions: "",
    price: 159,
    stockStatus: "low_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-005",
    sku: "FOOD-001",
    nameCnSimplified: "",
    nameCnTraditional: "有機綠茶",
    nameEn: "Organic Green Tea",
    category: "食品",
    categoryId: "CAT-FOOD",
    brand: "TeaGarden",
    size: "100g",
    bbd: "2027-06-30",
    vat: 9,
    uom: "BOX",
    stock: 300,
    promotions: "New Arrival",
    price: 89,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-006",
    sku: "FOOD-002",
    nameCnSimplified: "",
    nameCnTraditional: "堅果禮盒",
    nameEn: "Assorted Nut Gift Box",
    category: "食品",
    categoryId: "CAT-FOOD",
    brand: "NaturalBite",
    size: "500g",
    bbd: "2026-12-31",
    vat: 9,
    uom: "BOX",
    stock: 150,
    promotions: "Holiday Special",
    price: 128,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-007",
    sku: "HOME-001",
    nameCnSimplified: "",
    nameCnTraditional: "陶瓷咖啡杯",
    nameEn: "Ceramic Coffee Mug",
    category: "家居",
    categoryId: "CAT-HOME",
    brand: "HomeArt",
    size: "350ml",
    bbd: "",
    vat: 13,
    uom: "PCS",
    stock: 500,
    promotions: "",
    price: 69,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-008",
    sku: "HOME-002",
    nameCnSimplified: "",
    nameCnTraditional: "竹製砧板",
    nameEn: "Bamboo Cutting Board",
    category: "家居",
    categoryId: "CAT-HOME",
    brand: "EcoKitchen",
    size: "30x20cm",
    bbd: "",
    vat: 13,
    uom: "PCS",
    stock: 30,
    promotions: "",
    price: 45,
    stockStatus: "low_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-009",
    sku: "SPORT-001",
    nameCnSimplified: "",
    nameCnTraditional: "瑜伽墊",
    nameEn: "Yoga Mat",
    category: "運動",
    categoryId: "CAT-SPORT",
    brand: "FlexLife",
    size: "183x61cm",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 80,
    promotions: "",
    price: 118,
    stockStatus: "in_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
  {
    id: "prod-010",
    sku: "SPORT-002",
    nameCnSimplified: "",
    nameCnTraditional: "跑步水壺",
    nameEn: "Running Water Bottle",
    category: "運動",
    categoryId: "CAT-SPORT",
    brand: "HydroRun",
    size: "500ml",
    bbd: "",
    vat: 0,
    uom: "PCS",
    stock: 0,
    promotions: "",
    price: 55,
    stockStatus: "out_of_stock",
    imageUrl: "",
    createdAt: BigInt(Date.now()),
    updatedAt: BigInt(Date.now()),
  },
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "上海星光貿易有限公司",
    contactPerson: "張偉",
    phone: "021-5678-9012",
    email: "zhang@xingguang.com",
    address: "上海市浦東新區",
    createdAt: BigInt(Date.now()),
  },
  {
    id: "cust-002",
    name: "北京華美科技公司",
    contactPerson: "李明",
    phone: "010-8765-4321",
    email: "li@huamei.com",
    address: "北京市朝陽區",
    createdAt: BigInt(Date.now()),
  },
  {
    id: "cust-003",
    name: "廣州南方商貿",
    contactPerson: "王芳",
    phone: "020-3456-7890",
    email: "wang@nanfang.com",
    address: "廣州市天河區",
    createdAt: BigInt(Date.now()),
  },
  {
    id: "cust-004",
    name: "深圳創新企業",
    contactPerson: "陳雷",
    phone: "0755-9876-5432",
    email: "chen@chuangxin.com",
    address: "深圳市南山區",
    createdAt: BigInt(Date.now()),
  },
  {
    id: "cust-005",
    name: "杭州西湖零售",
    contactPerson: "趙麗",
    phone: "0571-2345-6789",
    email: "zhao@xihu.com",
    address: "杭州市西湖區",
    createdAt: BigInt(Date.now()),
  },
];
