/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContainerItem = IDL.Record({
  'id' : IDL.Text,
  'bbd' : IDL.Text,
  'qty' : IDL.Nat,
  'containerId' : IDL.Text,
  'productSku' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'productName' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AppUser = IDL.Record({
  'id' : IDL.Text,
  'totalOrders' : IDL.Nat,
  'joinDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'canEditContainers' : IDL.Bool,
  'mustChangePassword' : IDL.Bool,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'catCn' : IDL.Text,
  'catEn' : IDL.Text,
  'catId' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'subCat' : IDL.Text,
});
export const Container = IDL.Record({
  'id' : IDL.Text,
  'eta' : IDL.Text,
  'shipper' : IDL.Text,
  'status' : IDL.Text,
  'entryPort' : IDL.Text,
  'containerNo' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ExtendedProduct = IDL.Record({
  'bbd' : IDL.Text,
  'sku' : IDL.Text,
  'uom' : IDL.Text,
  'vat' : IDL.Float64,
  'categoryId' : IDL.Text,
  'promotions' : IDL.Text,
  'nameEn' : IDL.Text,
  'imageFileName' : IDL.Text,
  'size' : IDL.Text,
  'updatedAt' : IDL.Int,
  'stock' : IDL.Nat,
  'brand' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'salesRepId' : IDL.Text,
  'orderDate' : IDL.Int,
  'syncedAt' : IDL.Opt(IDL.Int),
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Text,
  'salesRepName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'stockStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'nameCnSimplified' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'nameCnTraditional' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'salesRep' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'totalOrders' : IDL.Nat,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'invitedBy' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContainerItem' : IDL.Func([ContainerItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createContainer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'deleteAppUser' : IDL.Func([IDL.Text], [], []),
  'deleteCategoryData' : IDL.Func([IDL.Text], [], []),
  'deleteContainer' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'submittedOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalCustomers' : IDL.Nat,
          'syncedOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], []),
  'getAllCategoriesData' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllExtendedProductsData' : IDL.Func(
      [],
      [IDL.Vec(ExtendedProduct)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAppUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getContainer' : IDL.Func([IDL.Text], [IDL.Opt(Container)], ['query']),
  'getContainerItems' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContainerItem)],
      ['query'],
    ),
  'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductBySku' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getTotalCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'orders' : IDL.Nat,
          'users' : IDL.Nat,
          'products' : IDL.Nat,
          'customers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
  'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
  'inviteUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeContainerItem' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
  'syncOrder' : IDL.Func([IDL.Text], [], []),
  'updateAppUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateContainer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContainerItem' : IDL.Func([ContainerItem], [], []),
  'updateProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'upsertAppUser' : IDL.Func([AppUser], [], []),
  'upsertCategory' : IDL.Func([Category], [], []),
  'upsertCustomer' : IDL.Func([Customer], [], []),
  'upsertExtendedProduct' : IDL.Func([ExtendedProduct], [], []),
  'upsertProductBySku' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContainerItem = IDL.Record({
    'id' : IDL.Text,
    'bbd' : IDL.Text,
    'qty' : IDL.Nat,
    'containerId' : IDL.Text,
    'productSku' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'productName' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AppUser = IDL.Record({
    'id' : IDL.Text,
    'totalOrders' : IDL.Nat,
    'joinDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'canEditContainers' : IDL.Bool,
    'mustChangePassword' : IDL.Bool,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'catCn' : IDL.Text,
    'catEn' : IDL.Text,
    'catId' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'subCat' : IDL.Text,
  });
  const Container = IDL.Record({
    'id' : IDL.Text,
    'eta' : IDL.Text,
    'shipper' : IDL.Text,
    'status' : IDL.Text,
    'entryPort' : IDL.Text,
    'containerNo' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ExtendedProduct = IDL.Record({
    'bbd' : IDL.Text,
    'sku' : IDL.Text,
    'uom' : IDL.Text,
    'vat' : IDL.Float64,
    'categoryId' : IDL.Text,
    'promotions' : IDL.Text,
    'nameEn' : IDL.Text,
    'imageFileName' : IDL.Text,
    'size' : IDL.Text,
    'updatedAt' : IDL.Int,
    'stock' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'salesRepId' : IDL.Text,
    'orderDate' : IDL.Int,
    'syncedAt' : IDL.Opt(IDL.Int),
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Text,
    'salesRepName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'stockStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'nameCnSimplified' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'nameCnTraditional' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'salesRep' : IDL.Null, 'admin' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'totalOrders' : IDL.Nat,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'invitedBy' : IDL.Opt(IDL.Text),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContainerItem' : IDL.Func([ContainerItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createContainer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'deleteAppUser' : IDL.Func([IDL.Text], [], []),
    'deleteCategoryData' : IDL.Func([IDL.Text], [], []),
    'deleteContainer' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'submittedOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalCustomers' : IDL.Nat,
            'syncedOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], []),
    'getAllCategoriesData' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllExtendedProductsData' : IDL.Func(
        [],
        [IDL.Vec(ExtendedProduct)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAppUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getContainer' : IDL.Func([IDL.Text], [IDL.Opt(Container)], ['query']),
    'getContainerItems' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContainerItem)],
        ['query'],
      ),
    'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductBySku' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getTotalCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'orders' : IDL.Nat,
            'users' : IDL.Nat,
            'products' : IDL.Nat,
            'customers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
    'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
    'inviteUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeContainerItem' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
    'syncOrder' : IDL.Func([IDL.Text], [], []),
    'updateAppUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateContainer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContainerItem' : IDL.Func([ContainerItem], [], []),
    'updateProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'upsertAppUser' : IDL.Func([AppUser], [], []),
    'upsertCategory' : IDL.Func([Category], [], []),
    'upsertCustomer' : IDL.Func([Customer], [], []),
    'upsertExtendedProduct' : IDL.Func([ExtendedProduct], [], []),
    'upsertProductBySku' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };