/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'salesRepId' : string,
  'orderDate' : bigint,
  'syncedAt' : [] | [bigint],
  'totalAmount' : number,
  'customerId' : string,
  'salesRepName' : string,
}
export interface OrderItem {
  'id' : string,
  'sku' : string,
  'productId' : string,
  'productName' : string,
  'orderId' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'subtotal' : number,
}
export interface Product {
  'id' : string,
  'sku' : string,
  'stockStatus' : string,
  'createdAt' : bigint,
  'nameCnSimplified' : string,
  'updatedAt' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
  'nameCnTraditional' : string,
}
export type UserRole = { 'salesRep' : null } |
  { 'admin' : null };
export interface _SERVICE {
  'createAdminUser' : ActorMethod<[string, string, string], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'submittedOrders' : bigint,
      'totalUsers' : bigint,
      'totalCustomers' : bigint,
      'syncedOrders' : bigint,
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByUser' : ActorMethod<[string], Array<Order>>,
  'getProductsBySku' : ActorMethod<[string], Product>,
  'getTotalCounts' : ActorMethod<
    [],
    {
      'orders' : bigint,
      'users' : bigint,
      'products' : bigint,
      'customers' : bigint,
    }
  >,
  'getUserRole' : ActorMethod<[string], UserRole>,
  'incrementUserOrderCount' : ActorMethod<[string], undefined>,
  'inviteUser' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'seedData' : ActorMethod<[], undefined>,
  'submitOrder' : ActorMethod<[Order, Array<OrderItem>], undefined>,
  'syncOrder' : ActorMethod<[string], undefined>,
  'upsertProductBySku' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];