/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'salesRepId' : string,
  'orderDate' : bigint,
  'syncedAt' : [] | [bigint],
  'totalAmount' : number,
  'customerId' : string,
  'salesRepName' : string,
}
export interface OrderItem {
  'id' : string,
  'sku' : string,
  'productId' : string,
  'productName' : string,
  'orderId' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'subtotal' : number,
}
export interface Product {
  'id' : string,
  'sku' : string,
  'imageBlob' : [] | [ExternalBlob],
  'stockStatus' : string,
  'createdAt' : bigint,
  'nameCnSimplified' : string,
  'updatedAt' : bigint,
  'category' : string,
  'price' : number,
  'nameCnTraditional' : string,
}
export type UserRole = { 'salesRep' : null } |
  { 'admin' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createAdminUser' : ActorMethod<[string, string, string], undefined>,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'submittedOrders' : bigint,
      'totalUsers' : bigint,
      'totalCustomers' : bigint,
      'syncedOrders' : bigint,
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByUser' : ActorMethod<[string], Array<Order>>,
  'getProductBySku' : ActorMethod<[string], Product>,
  'getProductImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getTotalCounts' : ActorMethod<
    [],
    {
      'orders' : bigint,
      'users' : bigint,
      'products' : bigint,
      'customers' : bigint,
    }
  >,
  'getUserRole' : ActorMethod<[string], UserRole>,
  'incrementUserOrderCount' : ActorMethod<[string], undefined>,
  'inviteUser' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'seedData' : ActorMethod<[], undefined>,
  'submitOrder' : ActorMethod<[Order, Array<OrderItem>], undefined>,
  'syncOrder' : ActorMethod<[string], undefined>,
  'updateProductImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'upsertProductBySku' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];