/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContainerItem = IDL.Record({
  'id' : IDL.Text,
  'bbd' : IDL.Text,
  'qty' : IDL.Nat,
  'containerId' : IDL.Text,
  'productSku' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'productName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Container = IDL.Record({
  'id' : IDL.Text,
  'eta' : IDL.Text,
  'shipper' : IDL.Text,
  'status' : IDL.Text,
  'entryPort' : IDL.Text,
  'containerNo' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'salesRepId' : IDL.Text,
  'orderDate' : IDL.Int,
  'syncedAt' : IDL.Opt(IDL.Int),
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Text,
  'salesRepName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'stockStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'nameCnSimplified' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'nameCnTraditional' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'salesRep' : IDL.Null,
  'admin' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addContainerItem' : IDL.Func([ContainerItem], [], []),
  'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createContainer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'deleteContainer' : IDL.Func([IDL.Text], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'submittedOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalCustomers' : IDL.Nat,
          'syncedOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getContainer' : IDL.Func([IDL.Text], [IDL.Opt(Container)], ['query']),
  'getContainerItems' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContainerItem)],
      ['query'],
    ),
  'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductBySku' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getTotalCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'orders' : IDL.Nat,
          'users' : IDL.Nat,
          'products' : IDL.Nat,
          'customers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
  'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
  'inviteUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'removeContainerItem' : IDL.Func([IDL.Text], [], []),
  'seedData' : IDL.Func([], [], []),
  'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
  'syncOrder' : IDL.Func([IDL.Text], [], []),
  'updateContainer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContainerItem' : IDL.Func([ContainerItem], [], []),
  'updateProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'upsertProductBySku' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContainerItem = IDL.Record({
    'id' : IDL.Text,
    'bbd' : IDL.Text,
    'qty' : IDL.Nat,
    'containerId' : IDL.Text,
    'productSku' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'productName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Container = IDL.Record({
    'id' : IDL.Text,
    'eta' : IDL.Text,
    'shipper' : IDL.Text,
    'status' : IDL.Text,
    'entryPort' : IDL.Text,
    'containerNo' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'salesRepId' : IDL.Text,
    'orderDate' : IDL.Int,
    'syncedAt' : IDL.Opt(IDL.Int),
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Text,
    'salesRepName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'stockStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'nameCnSimplified' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'nameCnTraditional' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'salesRep' : IDL.Null, 'admin' : IDL.Null });
  const OrderItem = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addContainerItem' : IDL.Func([ContainerItem], [], []),
    'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createContainer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'deleteContainer' : IDL.Func([IDL.Text], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'submittedOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalCustomers' : IDL.Nat,
            'syncedOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllContainers' : IDL.Func([], [IDL.Vec(Container)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getContainer' : IDL.Func([IDL.Text], [IDL.Opt(Container)], ['query']),
    'getContainerItems' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContainerItem)],
        ['query'],
      ),
    'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductBySku' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getTotalCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'orders' : IDL.Nat,
            'users' : IDL.Nat,
            'products' : IDL.Nat,
            'customers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
    'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
    'inviteUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'removeContainerItem' : IDL.Func([IDL.Text], [], []),
    'seedData' : IDL.Func([], [], []),
    'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
    'syncOrder' : IDL.Func([IDL.Text], [], []),
    'updateContainer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContainerItem' : IDL.Func([ContainerItem], [], []),
    'updateProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'upsertProductBySku' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };