/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : string,
  'totalOrders' : bigint,
  'joinDate' : string,
  'createdAt' : bigint,
  'role' : string,
  'fullName' : string,
  'email' : string,
  'passwordHash' : string,
  'canEditContainers' : boolean,
  'mustChangePassword' : boolean,
}
export interface Category {
  'id' : string,
  'catCn' : string,
  'catEn' : string,
  'catId' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'subCat' : string,
}
export interface Container {
  'id' : string,
  'eta' : string,
  'shipper' : string,
  'status' : string,
  'entryPort' : string,
  'containerNo' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'notes' : string,
}
export interface ContainerItem {
  'id' : string,
  'bbd' : string,
  'qty' : bigint,
  'containerId' : string,
  'productSku' : string,
  'sellingPrice' : number,
  'productName' : string,
}
export interface Customer {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ExtendedProduct {
  'bbd' : string,
  'sku' : string,
  'uom' : string,
  'vat' : number,
  'categoryId' : string,
  'promotions' : string,
  'nameEn' : string,
  'imageFileName' : string,
  'size' : string,
  'updatedAt' : bigint,
  'stock' : bigint,
  'brand' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'salesRepId' : string,
  'orderDate' : bigint,
  'syncedAt' : [] | [bigint],
  'totalAmount' : number,
  'customerId' : string,
  'salesRepName' : string,
}
export interface OrderItem {
  'id' : string,
  'sku' : string,
  'productId' : string,
  'productName' : string,
  'orderId' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'subtotal' : number,
}
export interface Product {
  'id' : string,
  'sku' : string,
  'imageBlob' : [] | [ExternalBlob],
  'stockStatus' : string,
  'createdAt' : bigint,
  'nameCnSimplified' : string,
  'updatedAt' : bigint,
  'category' : string,
  'price' : number,
  'nameCnTraditional' : string,
}
export interface UserProfile {
  'id' : string,
  'totalOrders' : bigint,
  'createdAt' : bigint,
  'role' : UserRole,
  'invitedBy' : [] | [string],
  'fullName' : string,
  'email' : string,
}
export type UserRole = { 'salesRep' : null } |
  { 'admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContainerItem' : ActorMethod<[ContainerItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAdminUser' : ActorMethod<[string, string, string], undefined>,
  'createContainer' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'deleteAppUser' : ActorMethod<[string], undefined>,
  'deleteCategoryData' : ActorMethod<[string], undefined>,
  'deleteContainer' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'submittedOrders' : bigint,
      'totalUsers' : bigint,
      'totalCustomers' : bigint,
      'syncedOrders' : bigint,
    }
  >,
  'getAllAppUsers' : ActorMethod<[], Array<AppUser>>,
  'getAllCategoriesData' : ActorMethod<[], Array<Category>>,
  'getAllContainers' : ActorMethod<[], Array<Container>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllExtendedProductsData' : ActorMethod<[], Array<ExtendedProduct>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAppUserByEmail' : ActorMethod<[string], [] | [AppUser]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getContainer' : ActorMethod<[string], [] | [Container]>,
  'getContainerItems' : ActorMethod<[string], Array<ContainerItem>>,
  'getOrdersByUser' : ActorMethod<[string], Array<Order>>,
  'getProductBySku' : ActorMethod<[string], Product>,
  'getProductImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getTotalCounts' : ActorMethod<
    [],
    {
      'orders' : bigint,
      'users' : bigint,
      'products' : bigint,
      'customers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[string], UserRole>,
  'incrementUserOrderCount' : ActorMethod<[string], undefined>,
  'inviteUser' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeContainerItem' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'submitOrder' : ActorMethod<[Order, Array<OrderItem>], undefined>,
  'syncOrder' : ActorMethod<[string], undefined>,
  'updateAppUserPassword' : ActorMethod<[string, string], undefined>,
  'updateContainer' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateContainerItem' : ActorMethod<[ContainerItem], undefined>,
  'updateProductImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'upsertAppUser' : ActorMethod<[AppUser], undefined>,
  'upsertCategory' : ActorMethod<[Category], undefined>,
  'upsertCustomer' : ActorMethod<[Customer], undefined>,
  'upsertExtendedProduct' : ActorMethod<[ExtendedProduct], undefined>,
  'upsertProductBySku' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];