/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'salesRepId' : IDL.Text,
  'orderDate' : IDL.Int,
  'syncedAt' : IDL.Opt(IDL.Int),
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Text,
  'salesRepName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'stockStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'nameCnSimplified' : IDL.Text,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'nameCnTraditional' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'salesRep' : IDL.Null,
  'admin' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'submittedOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalCustomers' : IDL.Nat,
          'syncedOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductsBySku' : IDL.Func([IDL.Text], [Product], ['query']),
  'getTotalCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'orders' : IDL.Nat,
          'users' : IDL.Nat,
          'products' : IDL.Nat,
          'customers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
  'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
  'inviteUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'seedData' : IDL.Func([], [], []),
  'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
  'syncOrder' : IDL.Func([IDL.Text], [], []),
  'upsertProductBySku' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'salesRepId' : IDL.Text,
    'orderDate' : IDL.Int,
    'syncedAt' : IDL.Opt(IDL.Int),
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Text,
    'salesRepName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'stockStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'nameCnSimplified' : IDL.Text,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'nameCnTraditional' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'salesRep' : IDL.Null, 'admin' : IDL.Null });
  const OrderItem = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'createAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'submittedOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalCustomers' : IDL.Nat,
            'syncedOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByUser' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductsBySku' : IDL.Func([IDL.Text], [Product], ['query']),
    'getTotalCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'orders' : IDL.Nat,
            'users' : IDL.Nat,
            'products' : IDL.Nat,
            'customers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Text], [UserRole], ['query']),
    'incrementUserOrderCount' : IDL.Func([IDL.Text], [], []),
    'inviteUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'seedData' : IDL.Func([], [], []),
    'submitOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [], []),
    'syncOrder' : IDL.Func([IDL.Text], [], []),
    'upsertProductBySku' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };